version: '3'
services:
  stubby:
    image: "mvance/stubby:latest"
    networks:
      vlan0:
        ipv4_address: 172.16.0.103
        aliases:
          - "stubby"
    environment:
     - TZ=America/Sao_Paulo
    restart: unless-stopped
  unbound:
    image: "mvance/unbound:1.13.1-stubby"
    depends_on:
      - "stubby"    
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    networks:
      vlan0:
        ipv4_address: 172.16.0.104
        aliases:
          - "unbound"
    environment:
     - TZ=America/Sao_Paulo
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  vlan0:
    external:
      name: vlan0